# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.add_button = QtWidgets.QPushButton(Form)
        self.add_button.setGeometry(QtCore.QRect(410, 130, 75, 23))
        self.add_button.setObjectName("add_button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 60, 241, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 20, 331, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.show_button = QtWidgets.QPushButton(Form)
        self.show_button.setGeometry(QtCore.QRect(490, 130, 75, 23))
        self.show_button.setObjectName("show_button")
        self.line_key = QtWidgets.QLineEdit(Form)
        self.line_key.setGeometry(QtCore.QRect(80, 130, 301, 20))
        self.line_key.setObjectName("line_key")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 241, 16))
        self.label_2.setObjectName("label_2")
        self.line_str = QtWidgets.QLineEdit(Form)
        self.line_str.setGeometry(QtCore.QRect(80, 80, 481, 20))
        self.line_str.setObjectName("line_str")
        self.bloc_text = QtWidgets.QTextBrowser(Form)
        self.bloc_text.setGeometry(QtCore.QRect(80, 180, 481, 271))
        self.bloc_text.setObjectName("bloc_text")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_button.setText(_translate("Form", "Ajouter"))
        self.label.setText(_translate("Form", "Saisissez ici votre chaîne de caractères à crypter :"))
        self.label_3.setText(_translate("Form", "Bienvenue sur le CODE CODE CODEC"))
        self.show_button.setText(_translate("Form", "Afficher"))
        self.label_2.setText(_translate("Form", "Saisissez votre clé de cryptage :"))
